import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Link } from "react-router-dom";
import { 
  BookOpen, 
  Brain, 
  Target, 
  Users, 
  Sparkles, 
  ArrowRight,
  CheckCircle
} from "lucide-react";
import heroImage from "@/assets/hero-education.jpg";

const Landing = () => {
  const features = [
    {
      icon: Brain,
      title: "AI-Powered Roadmaps",
      description: "Get personalized learning paths generated by AI based on your goals and current skills"
    },
    {
      icon: BookOpen,
      title: "Curated Resources",
      description: "Access the best educational content from YouTube, books, courses, and expert communities"
    },
    {
      icon: Target,
      title: "Skill Tracking",
      description: "Monitor your progress and get recommendations for exams and certifications"
    },
    {
      icon: Users,
      title: "Learning Community",
      description: "Connect with learners worldwide and share your educational journey"
    }
  ];

  const benefits = [
    "Personalized AI roadmaps for any skill",
    "Curated resources from top platforms",
    "Progress tracking and analytics",
    "Expert community insights",
    "Exam preparation guidance",
    "Career advancement planning"
  ];

  return (
    <div className="min-h-screen bg-gradient-secondary">
      {/* Header */}
      <header className="container mx-auto px-4 py-6">
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-2">
            <div className="w-10 h-10 bg-gradient-primary rounded-lg flex items-center justify-center">
              <span className="text-white font-bold">SM</span>
            </div>
            <span className="font-bold text-2xl bg-gradient-primary bg-clip-text text-transparent">
              Skill-Metrics
            </span>
          </div>
          <div className="flex items-center space-x-4">
            <Button variant="ghost" asChild>
              <Link to="/login">Sign In</Link>
            </Button>
            <Button asChild>
              <Link to="/signup">Get Started</Link>
            </Button>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <section className="container mx-auto px-4 py-20">
        <div className="grid lg:grid-cols-2 gap-12 items-center">
          <div className="space-y-8 animate-fade-in">
            <div className="space-y-4">
              <h1 className="text-5xl lg:text-6xl font-bold leading-tight">
                Master Any{" "}
                <span className="bg-gradient-primary bg-clip-text text-transparent">
                  Skill
                </span>{" "}
                with AI-Powered Learning
              </h1>
              <p className="text-xl text-muted-foreground max-w-lg">
                Discover personalized learning paths, curated resources, and join a community 
                of learners advancing their careers through skill development.
              </p>
            </div>

            <div className="flex flex-col sm:flex-row gap-4">
              <Button size="lg" className="shadow-glow" asChild>
                <Link to="/signup">
                  Start Learning
                  <ArrowRight className="ml-2 h-5 w-5" />
                </Link>
              </Button>
              <Button size="lg" variant="outline" asChild>
                <Link to="/explore">
                  Explore Skills
                </Link>
              </Button>
            </div>

            <div className="flex items-center space-x-8 text-sm text-muted-foreground">
              <div className="flex items-center space-x-2">
                <CheckCircle className="h-4 w-4 text-success" />
                <span>Free to start</span>
              </div>
              <div className="flex items-center space-x-2">
                <CheckCircle className="h-4 w-4 text-success" />
                <span>AI-powered</span>
              </div>
              <div className="flex items-center space-x-2">
                <CheckCircle className="h-4 w-4 text-success" />
                <span>Expert curated</span>
              </div>
            </div>
          </div>

          <div className="relative animate-scale-in">
            <div className="absolute inset-0 bg-gradient-primary opacity-20 rounded-3xl blur-3xl"></div>
            <img
              src={heroImage}
              alt="Students learning with AI technology"
              className="relative rounded-3xl shadow-elevated w-full h-auto"
            />
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="container mx-auto px-4 py-20">
        <div className="text-center space-y-4 mb-16">
          <h2 className="text-4xl font-bold">
            Everything You Need to{" "}
            <span className="bg-gradient-primary bg-clip-text text-transparent">
              Excel
            </span>
          </h2>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            Our platform combines AI intelligence with human expertise to create 
            the most effective learning experience.
          </p>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
          {features.map((feature, index) => {
            const Icon = feature.icon;
            return (
              <Card 
                key={index} 
                className="p-6 text-center hover:shadow-elevated transition-all duration-300 hover:-translate-y-2 animate-fade-in"
                style={{ animationDelay: `${index * 0.1}s` }}
              >
                <div className="w-12 h-12 bg-gradient-primary rounded-lg flex items-center justify-center mx-auto mb-4">
                  <Icon className="h-6 w-6 text-white" />
                </div>
                <h3 className="text-lg font-semibold mb-2">{feature.title}</h3>
                <p className="text-muted-foreground text-sm">{feature.description}</p>
              </Card>
            );
          })}
        </div>
      </section>

      {/* Benefits Section */}
      <section className="container mx-auto px-4 py-20">
        <div className="grid lg:grid-cols-2 gap-16 items-center">
          <div className="space-y-8">
            <div className="space-y-4">
              <h2 className="text-4xl font-bold">
                Why Choose{" "}
                <span className="bg-gradient-primary bg-clip-text text-transparent">
                  Skill-Metrics?
                </span>
              </h2>
              <p className="text-xl text-muted-foreground">
                Join thousands of learners who are advancing their careers with our 
                comprehensive learning platform.
              </p>
            </div>

            <div className="grid gap-4">
              {benefits.map((benefit, index) => (
                <div 
                  key={index} 
                  className="flex items-center space-x-3 animate-fade-in"
                  style={{ animationDelay: `${index * 0.1}s` }}
                >
                  <CheckCircle className="h-5 w-5 text-success flex-shrink-0" />
                  <span className="text-foreground">{benefit}</span>
                </div>
              ))}
            </div>

            <Button size="lg" className="shadow-glow" asChild>
              <Link to="/signup">
                Join Our Community
                <Sparkles className="ml-2 h-5 w-5" />
              </Link>
            </Button>
          </div>

          <div className="space-y-6">
            <Card className="p-6 shadow-card">
              <div className="flex items-center space-x-4 mb-4">
                <div className="w-12 h-12 bg-gradient-primary rounded-full flex items-center justify-center">
                  <Brain className="h-6 w-6 text-white" />
                </div>
                <div>
                  <h3 className="font-semibold">AI Roadmap Generator</h3>
                  <p className="text-sm text-muted-foreground">Powered by advanced algorithms</p>
                </div>
              </div>
              <p className="text-sm text-muted-foreground">
                Our AI analyzes your current skills, learning preferences, and career goals 
                to create a personalized roadmap that adapts as you progress.
              </p>
            </Card>

            <Card className="p-6 shadow-card">
              <div className="flex items-center space-x-4 mb-4">
                <div className="w-12 h-12 bg-accent rounded-full flex items-center justify-center">
                  <Users className="h-6 w-6 text-white" />
                </div>
                <div>
                  <h3 className="font-semibold">Expert Community</h3>
                  <p className="text-sm text-muted-foreground">Learn from the best</p>
                </div>
              </div>
              <p className="text-sm text-muted-foreground">
                Connect with industry experts, join study groups, and get mentorship 
                from professionals who've walked the path you're on.
              </p>
            </Card>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="bg-gradient-hero py-20">
        <div className="container mx-auto px-4 text-center">
          <div className="max-w-3xl mx-auto space-y-8 text-white">
            <h2 className="text-4xl lg:text-5xl font-bold">
              Ready to Transform Your Learning Journey?
            </h2>
            <p className="text-xl opacity-90">
              Join thousands of learners who are already advancing their careers 
              with personalized AI-powered education.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Button size="lg" variant="secondary" className="shadow-elevated" asChild>
                <Link to="/signup">
                  Get Started Free
                  <ArrowRight className="ml-2 h-5 w-5" />
                </Link>
              </Button>
              <Button size="lg" variant="outline" className="border-white text-white hover:bg-white hover:text-primary" asChild>
                <Link to="/explore">
                  Explore Features
                </Link>
              </Button>
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-card border-t py-12">
        <div className="container mx-auto px-4">
          <div className="flex flex-col md:flex-row justify-between items-center">
            <div className="flex items-center space-x-2 mb-4 md:mb-0">
              <div className="w-8 h-8 bg-gradient-primary rounded-lg flex items-center justify-center">
                <span className="text-white font-bold text-sm">SM</span>
              </div>
              <span className="font-bold text-xl bg-gradient-primary bg-clip-text text-transparent">
                Skill-Metrics
              </span>
            </div>
            <p className="text-muted-foreground text-sm">
              © 2024 Skill-Metrics. Empowering learners worldwide.
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default Landing;