// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vecdjxbrkaqpvftwoafj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlY2RqeGJya2FxcHZmdHdvYWZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNTg0OTksImV4cCI6MjA3MzgzNDQ5OX0.5MlACmnknf5dki0JMSNimzMJbJEf9M4V2_VzPq8mOqw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database, 'public'>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

export type TypedSupabaseClient = typeof supabase;